### ISSUE TITLE
feature request : user setting for threshold / stop automatic zone-switching

### ISSUE THREAD

**Issue by issuemaker2** [wingman-jr-addon/wingman_jr#80]
hello, thank you for a perfect firefox addon.

i want a setting so that : 
1. i can set a threshold that is preserved between firefox restart
2. the threshold/zone won't change automatically by extension

**Comment by wingman-jr-addon** [comment]
Hi @issuemaker2 !

I'd like to make sure I'm understanding your request. Right now with the addon, you can turn off the "automatic zone" feature - but that isn't preserved when Firefox restarts.

So you would like to:
a) Preserve the "automatic zone" setting as on or off when Firefox restarts AND
b) If you have "automatic zone" setting turned off, then remember which zone the user manually selected

Is that what you're asking?

**Comment by issuemaker2** [comment]
i want to set `zoneThreshold` manually which is preserved between restarts, and turn off automatic zone setting completely.

**Comment by wingman-jr-addon** [comment]
The automatic zone thing seems like something with general appeal and straightforward to implement.

However, `zoneThreshold` is a (purposely) internal variable that is based on the ROC of the model. If I upgrade the model to a new one, the old saved threshold will almost certainly be the wrong choice. See for example [the appendix with the ROC/threshold table over here](https://github.com/wingman-jr-addon/model/tree/master/sqrxr_62) relative to say a [different ROC](https://github.com/wingman-jr-addon/wingman_jr/blob/sqrxr_105-and-roc/roc.js#L2256).
I've thought about exposing a "sensitivity" slider of some sort as well, but the thing there is that similarly the nonlinearity of the underlying curve fitting might be a bit different across different models.
Basically, I don't want to get future bug reports like "I upgraded and the model got worse!" due to the user not adjusting thresholds.

Another related aspect of this is also how one would go about tuning the threshold in the first place as a user. There are interesting questions here technically and from a user experience perspective. From a technical perspective, because the filtering is done in the stream, it'd be harder to see changes in realtime on a page because you have to do a deep refresh - and there isn't a particularly good "preview" type of option right now. From a user experience perspective, it might also be hard to tune it without seeing how it would act on a range of content, some of it likely objectionable.

At any rate - that's how I got to the idea of zones - leaving it at a very coarse "trusted", "neutral", and "untrusted". That's a concept I can likely map to future models as well. I could maybe go as high as five zones to add a bit more gradation if desired, but would be a bit hesitant to go much deeper than that.

So the big thing is I'm trying to keep this part simple in the name of being user-focused even though it seems like a nice power user feature. If it did exist, how do you think you'd use it on a day to day basis?

**Comment by issuemaker2** [comment]
i see all those valid points, and that's why i tried to make local modification instead of making feature request, but i wasn't able to install unsigned xpi on my firefox developer edition for some reason.  😭  as it's my first time working with addons, can you help me personally?

the intended usage : for some unclear reasons (i suspect something fp16 related) i found almost all (very clear) negatives resulted in value between `0.0006` and `0.00061`. i tested `zoneThreshold` of `0.00061` and it did not interfere with my usual academic web browsing and helped me fighting from distraction, so i just wanted to add that as a permanent setting.

**Comment by wingman-jr-addon** [comment]
Sure, hopefully I can help you! Please be aware if you are on FF83/84, I'm currently [experiencing this major performance issue](https://github.com/wingman-jr-addon/wingman_jr/issues/75) - you may not experience it but please be aware!

Regarding an unsigned XPI - I don't go that route.
To load this up in Firefox it's actually quite simply usually!

1. Clone the repo.
2. In Firefox, go to the page about:debugging, pick "This Firefox" on the left, then "Load Temporary Addon" and select the manifest.json file from the repo. You will likely exhibit a several second hang as the addon loads.
3. Optional - given the nature of the addon, you may wish to be doing some work in a Private window. For addons, that's an extra permission. After the temporary addon is loaded, go to about:addons, "manage" Wingman Jr., and change the option to "Allow in Private Windows". Do note that changing that setting seems to do some level of reloading, so you may experience the same initial load time.

I'm doing my best to keep the addon small and not involve extra build steps and/or e.g. `npm`; it makes my life a bit easier in some ways and it also keeps the submission process a bit simpler. It also makes life easier for people like you to load it up!

Also, it appeared that you perhaps meant to say more but your comment got cut off?

**Comment by issuemaker2** [comment]
Thank you for your help! Actually i found that signing the addon was very easy, and just signed it. :smiley: 

As a layman without technological background, it feels strange that FF83/84 acceleration "bug" was actually a fix, and i'll need to resort to `about:config` customization. 

Again, thank you for your help, and i'm closing the issue :hand:

**Comment by wingman-jr-addon** [comment]
Say @issuemaker2 I've been working the performance angle. Given the nature of the issue the hacky workaround is to simply not have Tensorflow.js use `failIfMajorPerformanceCaveat:true`, and let it create the canvas regardless. If it was decent performance in FF82, it'll be decent performance still. One easy way to do this is to monkey patch the existing tfjs_2.7.0.js with e.g. `failIfMajorPerformanceCaveat:!1` to have it be false (keeping in mind that Tensorflow.js is Apache v2 licensed I believe). I'm a bit hesitant to turn this on for everybody quite yet as [there might be a cleaner way coming at some point](https://github.com/tensorflow/tfjs/issues/4347) - and more fundamentally there are probably some folks for whom WASM is good but WebGL is bad.
